telegram_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: admin
      port: 5432
      dbname: telegram2
      schema: analytics # your final data mart layer
      threads: 1
