version: 2

models:
  - name: stg_telegram_messages
    description: "Staging cleaned version of raw.telegram_messages"
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
